export class Ville {
    private villes: string[][] = [

     [
        "",
        "Ariana Essoughra",
        "Ariana Ville",
        "Borj Louzir",
        "Charguia 1",
        "Charguia 2",
        "Chotrana",
        "Chotrana 1",
        "Chotrana 2",
        "Chotrana 3",
        "Cit� Ennasr 1",
        "Cit� Ennasr 2",
        "Cite Ennkhillet",
        "Cit� Hedi Nouira",
        "Dar Fadhal",
        "El Menzah 5",
        "El Menzah 6",
        "El Menzah 7",
        "El Menzah 8",
        "Ennasr",
        "Ettadhamen",
        "Ghazela",
        "Jardins El Menzah",
        "Kalaat Landlous",
        "La Soukra",
        "Les jardins El Menzah1",
        "Les jardins El Menzah2",
        "Mnihla",
        "Nouvelle Ariana",
        "Raoued",
        "Riadh Andalous",
        "Sidi Thabet"
    ],

    [
        "Amdoun",
        "Beja Nord",
        "Beja Sud",
        "El ksar",
        "Goubellat",
        "Mejez El Bab",
        "Nefza",
        "Teboursouk",
        "Testour",
        "Thibar"
    ],

   [
        "",
        "Ben Arous",
        "Borj cedria",
        "Bou Mhel El Bassatine",
        "El Mourouj",
        "El Mourouj 1",
        "El Mourouj 3",
        "El Mourouj 4",
        "El Mourouj 5",
        "El Mourouj 6",
        "Ezzahra",
        "Fouchana",
        "Hammam Chatt",
        "Hammam Lif",
        "Megrine",
        "Mohamadia",
        "Mornag",
        "Nouvelle Medina",
        "Rades",
        "Sidi Rezig"
    ],

    [
        "Bizerte",
        "Bizerte Nord",
        "Bizerte Sud",
        "El Alia",
        "Ghar El Melh",
        "Ghezala",
        "Jarzouna",
        "Joumine",
        "Mateur",
        "Menzel Bourguiba",
        "Menzel Jemil",
        "Ras Jebel",
        "Sejnane",
        "Tinja",
        "Utique"
    ],

    [
        "El Hamma",
        "El Metouia",
        "Gab�s",
        "Gabes Medina",
        "Gabes Ouest",
        "Gabes Sud",
        "Ghannouche",
        "Mareth",
        "Matmata",
        "Menzel Habib",
        "Nouvelle Matmata"
    ],

 [
        "",
        "Belkhir",
        "El Guettar",
        "El Ksar",
        "El Mdhilla",
        "Gafsa Nord",
        "Gafsa Sud",
        "Metlaoui",
        "Moulares",
        "Oum El Araies",
        "Redeyef",
        "Sidi Aich",
        "Sned"
    ],

  [
        "Ain Draham",
        "Balta Bou Aouene",
        "Bou Salem",
        "Fernana",
        "Ghardimaou",
        "Jendouba",
        "Jendouba Nord",
        "Oued Mliz",
        "Tabarka"
    ],

    [
        "Bou Hajla",
        "Chebika",
        "Cherarda",
        "El Ala",
        "Haffouz",
        "Hajeb El Ayoun",
        "Kairouan Nord",
        "Kairouan Sud",
        "Nasrallah",
        "Oueslatia",
        "Sbikha"
    ],

   [
        "",
        "El Ayoun",
        "Ezzouhour (Kasserine)",
        "Feriana",
        "Foussana",
        "Haidra",
        "Hassi El Frid",
        "Jediliane",
        "Kasserine Nord",
        "Kasserine Sud",
        "Mejel Bel Abbes",
        "Sbeitla",
        "Sbiba",
        "Thala"
    ],

 [
        "Douz",
        "Douz Nord",
        "Douz Sud",
        "El Faouar",
        "Kébili",
        "Kebili Nord",
        "Kebili Sud",
        "Souk El Ahad"
    ],

   [
        "Borj El Amri",
        "Denden",
        "Douar Hicher",
        "El Battan",
        "Jedaida",
        "Mannouba",
        "Manouba Ville",
        "Manzel El Habib",
        "Mornaguia",
        "Oued Ellil",
        "Tebourba"
    ],

     [
        "Dahmani",
        "El Ksour",
        "Jerissa",
        "Kalaa El Khasba",
        "Kalaat Sinane",
        "Le Kef Est",
        "Le Kef Ouest",
        "Le Sers",
        "Nebeur",
        "Sakiet Sidi Youssef",
        "Tajerouine",
        "Touiref"
    ],

    [
        "",
        "Bou Merdes",
        "Chorbane",
        "El Jem",
        "Hbira",
        "Ksour Essaf",
        "La Chebba",
        "Mahdia",
        "Melloulech",
        "Ouled Chamakh",
        "Sidi Alouene",
        "Souassi"
    ],

     [
        "", // Ajoutez une option vide si nécessaire
        "Ajim",
        "Ben Guerdane",
        "Beni Khedache",
        "Djerba - Houmet Essouk",
        "Djerba - Midoun",
        "Médenine",
        "Medenine Nord",
        "Medenine Sud",
        "Sidi Makhlouf",
        "Zarzis"
    ],

    [
        "Bekalta",
        "Bembla",
        "Beni Hassen",
        "Jemmal",
        "Ksar Helal",
        "Ksibet El Mediouni",
        "Moknine",
        "Monastir",
        "Ouerdanine",
        "Sahline",
        "Sayada Lamta Bou Hajar",
        "Teboulba",
        "Zeramdine"
    ],

    [
        "",
        "Beni Khalled",
        "Beni Khiar",
        "Bou Argoub",
        "Dar Chaabane Elfehri",
        "El Haouaria",
        "El Mida",
        "Grombalia",
        "Hammam El Ghezaz",
        "Hammamet",
        "Hammamet Centre",
        "Hammamet Nord",
        "Kelibia",
        "Korba",
        "Menzel Bouzelfa",
        "Menzel Temime",
        "Mrezga",
        "Nabeul",
        "Soliman",
        "Takelsa"
    ],

  [
        "",
        "Agareb",
        "Bir Ali Ben Khelifa",
        "El Amra",
        "El Hencha",
        "Esskhira",
        "Ghraiba",
        "Jebeniana",
        "Kerkenah",
        "Mahras",
        "Menzel Chaker",
        "Route De Gab�s",
        "Route de l'a�roport",
        "Route El Afrane",
        "Route El Ain",
        "Route Gremda",
        "Route Maehdia",
        "Route Manzel Chaker",
        "Route MHARZA",
        "Route Saltania",
        "Route Soukra",
        "Route Taniour",
        "Route TUNIS",
        "Sakiet Eddaier",
        "Sakiet Ezzit",
        "Sfax Est",
        "Sfax M�dina",
        "Sfax Sud",
        "Sfax Ville",
        "Thyna"
    ],

  ["Ben Oun", "Bir El Haffey", "Cebbala", "Jilma", "Maknassy", "Menzel Bouzaiene", "Mezzouna", "Ouled Haffouz", "Regueb", "Sidi Bouzid", "Sidi Bouzid Est", "Sidi Bouzid Ouest", "Souk Jedid"],

  [
        "",
        "Bargou",
        "Bou Arada",
        "El Aroussa",
        "Gaafour",
        "Kesra",
        "Le Krib",
        "Makthar",
        "Rohia",
        "Sidi Bou Rouis",
        "Siliana",
        "Siliana Nord",
        "Siliana Sud"
    ],

  [
        "Akouda",
        "Bou Ficha",
        "Chatt mariem",
        "Enfidha",
        "Hammam Sousse",
        "Hergla",
        "Kalaa El Kebira",
        "Kalaa Essghira",
        "Kantaoui",
        "Khzema",
        "Kondar",
        "Msaken",
        "Sahloul",
        "Sidi Bou Ali",
        "Sidi El Heni",
        "Sousse",
        "Sousse Jaouhara",
        "Sousse Riadh",
        "Sousse Sidi Abdelhamid",
        "Sousse Ville",
        "Zaouit Ksibat Thrayett"
    ],

  [
        "",
        "Bir Lahmar",
        "Dhehiba",
        "Ghomrassen",
        "Remada",
        "Smar",
        "Tataouine",
        "Tataouine Nord",
        "Tataouine Sud"
    ],

    [
        "Agba",
        "Ain Zaghouan",
        "Ain Zaghouan",
        "Ain Zaghouan Nord",
        "Ain Zaghouan Sud",
        "Bab Bhar",
        "Bab Souika",
        "Bellevue",
        "Carthage",
        "Centre Urbain Nord",
        "Centre Ville Lafayette",
        "Cite El Khadra",
        "Cit� Olympique",
        "El Hrairia",
        "El Kabbaria",
        "El Kram",
        "El manar 1",
        "El manar 2",
        "El Menzah",
        "El Menzah 1",
        "El Menzah 4",
        "El Menzah 9",
        "El Omrane",
        "El Omrane Superieur",
        "El Ouerdia",
        "Essijoumi",
        "Ettahrir",
        "Ezzouhour (Tunis)",
        "Gammarth",
        "Jardins de carthage",
        "Jebel Jelloud",
        "Khaznadar",
        "Kheireddine Pacha",
        "Ksar said",
        "L'aouina",
        "La Goulette",
        "La Marsa",
        "La Medina",
        "Lac 1",
        "Lac 2",
        "Le Bardo",
        "Monfleury",
        "Montplaisir",
        "Mutuelleville",
        "Sidi bou said",
        "Sidi Daoud",
        "Sidi El Bechir",
        "Sidi Hassine",
        "Tunis",
        "Tunis Belvedere"
    ],

     [
        "Bir Mcherga",
        "El Fahs",
        "Ennadhour",
        "Hammam Zriba",
        "Saouef",
        "Zaghouan"
    ]]

 
    getVillesByGouvernement(i:number){
        return this.villes[i-1]
        
    }
}

